name: IPTV(v4) Resources Update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_filters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get IPTV Resources files
        run: |
          update_time=$(TZ='Asia/Shanghai' date '+%m/%d/%Y %H:%M:%S')
          url="https://raw.githubusercontent.com/vbskycn/iptv/master/tv/iptv4.m3u"
          echo "正在处理 v4live.txt..."
          curl -sSL "$url" > v4live.txt || echo "获取文件失败"

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update v4 live"
            git push
          else
            echo "No changes."
          fi
